name: CI

on:
  push:
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Ruby 3.0
        uses: actions/setup-ruby@v1
        with:
          ruby-version: 3.0.x
      - name: Setup Bundler
        run: gem install bundler:2.3.8

      - name: Install dependencies
        run: make install

      - name: Run Rubocop
        run: make lint

      - name: Minitest
        run: make test